import{useEffect,useState}from"react";import{api}from"./lib/api";
type Field={key:string,type:string,label:string,options?:string[]};
const copy:any={en:{tag:"AI roommate matching for Tunisia",title:"Find someone who fits your life.",sub:"Binomi compares the things that actually matter in a shared home — budget, routines, location, hobbies and deal-breakers.",start:"Start matching",name:"Your name",continue:"Continue",profile:"Your profile",save:"Save profile",candidates:"Find roommates",matches:"My matches",clone:"My clone",back:"Back",match:"Run AI match",loading:"Negotiating…",strong:"Strong",conditional:"Conditional",incompatible:"Incompatible",why:"Why this match?",negotiation:"Clone negotiation",send:"Send",placeholder:"Ask your clone anything…",saved:"Profile saved.",no:"No profiles yet."},fr:{tag:"Matching IA de colocataires en Tunisie",title:"Trouvez quelqu’un qui vous correspond.",sub:"Binomi compare budget, habitudes, localisation, loisirs et points non négociables.",start:"Commencer",name:"Votre nom",continue:"Continuer",profile:"Votre profil",save:"Enregistrer",candidates:"Trouver des colocataires",matches:"Mes matchs",clone:"Mon clone",back:"Retour",match:"Lancer le match IA",loading:"Négociation…",strong:"Fort",conditional:"Conditionnel",incompatible:"Incompatible",why:"Pourquoi ce match ?",negotiation:"Négociation des clones",send:"Envoyer",placeholder:"Posez une question à votre clone…",saved:"Profil enregistré.",no:"Aucun profil pour le moment."},ar:{tag:"مطابقة السكن بالذكاء الاصطناعي في تونس",title:"اعثر على شخص يناسب أسلوب حياتك.",sub:"يقارن Binomi الميزانية والعادات والموقع والهوايات والأمور غير القابلة للتفاوض.",start:"ابدأ المطابقة",name:"اسمك",continue:"متابعة",profile:"ملفك",save:"حفظ الملف",candidates:"ابحث عن شريك سكن",matches:"مطابقاتي",clone:"نسختي",back:"رجوع",match:"ابدأ المطابقة بالذكاء الاصطناعي",loading:"جاري التفاوض…",strong:"قوي",conditional:"مشروط",incompatible:"غير متوافق",why:"لماذا هذا التطابق؟",negotiation:"تفاوض النسخ",send:"إرسال",placeholder:"اسأل نسختك أي شيء…",saved:"تم حفظ الملف.",no:"لا توجد ملفات بعد."}};
function statusLabel(s:string,l:string){return copy[l][s]||s}
export default function App(){
 const[lang,setLang]=useState(localStorage.getItem("binomi_lang")||"en"); const[t,setT]=useState(copy[lang]);
 const[user,setUser]=useState<any>(null); const[view,setView]=useState("home"); const[fields,setFields]=useState<Field[]>([]); const[q,setQ]=useState<any>({}); const[candidates,setCandidates]=useState<any[]>([]); const[matches,setMatches]=useState<any[]>([]); const[selected,setSelected]=useState<any>(null); const[log,setLog]=useState<any>(null); const[loading,setLoading]=useState(false); const[error,setError]=useState(""); const[name,setName]=useState(""); const[messages,setMessages]=useState<any[]>([]); const[input,setInput]=useState(""); const[session,setSession]=useState<string|null>(null);
 useEffect(()=>{setT(copy[lang]);localStorage.setItem("binomi_lang",lang)},[lang]);
 useEffect(()=>{const id=localStorage.getItem("binomi_user");if(id)api.matches(id).then(x=>setMatches(x.matches)).catch(()=>{})},[]);
 const enter=async()=>{if(!name.trim())return;setLoading(true);try{const u=await api.enter(name,lang);setUser(u);localStorage.setItem("binomi_user",u.id);const s=await api.schema(lang);setFields(s.fields);setQ(u.questionnaire||{});setView(Object.keys(u.questionnaire||{}).length?"home":"questionnaire")}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const save=async()=>{setLoading(true);try{await api.saveQuestionnaire(user.id,q,lang);setView("candidates");await loadCandidates()}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const loadCandidates=async()=>{const x=await api.candidates(user.id);setCandidates(x.candidates);};
 const run=async(c:any)=>{setLoading(true);setError("");try{const x=await api.runMatch(user.id,c.id,lang);setSelected(x.match);setLog(x.negotiation);setView("result");const m=await api.matches(user.id);setMatches(m.matches)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const loadMatches=async()=>{const x=await api.matches(user.id);setMatches(x.matches);setView("matches")};
 const openLog=async(m:any)=>{setLoading(true);try{const x=await api.negotiation(m.negotiation_log_id);setSelected(m);setLog(x);setView("result")}finally{setLoading(false)}};
 const cloneIntro=async()=>{try{const x=await api.cloneIntro(user.id);setMessages([{role:"assistant",content:x.intro}]);setView("clone")}catch(e:any){setError((e as Error).message)}};
 const send=async()=>{if(!input.trim()||loading)return;const msg=input.trim();setInput("");const next=[...messages,{role:"user",content:msg}];setMessages(next);setLoading(true);try{const x=await api.cloneChat({user_id:user.id,message:msg,history:messages,language:lang,session_id:session});setSession(x.session_id);setMessages([...next,{role:"assistant",content:x.reply}])}finally{setLoading(false)}};
 if(!user)return <div className="app"><nav className="nav"><div className="logo">Bi<span>no</span>mi</div><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">EN</option><option value="fr">FR</option><option value="ar">AR</option></select></nav><main className="hero"><div className="container"><p className="muted">{t.tag}</p><h1>Find someone who <span>fits.</span></h1><p>{t.sub}</p><div className="card form"><div className="field"><label>{t.name}</label><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&enter()} placeholder="Rayen"/></div><div className="actions"><button className="btn primary" onClick={enter} disabled={loading}>{loading?t.loading:t.continue}</button></div></div></div></main></div>;
 return <div className={"app "+(lang==="ar"?"rtl":"")}><nav className="nav"><button className="logo" onClick={()=>setView("home")}>Bi<span>no</span>mi</button><div className="navlinks"><button onClick={()=>{setView("home")}}>{t.profile}</button><button onClick={loadCandidates}>{t.candidates}</button><button onClick={loadMatches}>{t.matches}</button><button onClick={cloneIntro}>{t.clone}</button></div><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">EN</option><option value="fr">FR</option><option value="ar">AR</option></select></nav><main className="container">{error&&<div className="notice">{error}</div>}
 {view==="home"&&<><div className="toolbar"><div><h1>{t.profile}</h1><p className="muted">{user.name}</p></div><button className="btn primary" onClick={()=>{setView("questionnaire");api.schema(lang).then(x=>setFields(x.fields))}}>{t.profile}</button></div><div className="card"><h2>Binomi</h2><p className="muted">{t.sub}</p><div className="actions"><button className="btn primary" onClick={loadCandidates}>{t.candidates}</button><button className="btn light" onClick={loadMatches}>{t.matches}</button></div></div></>}
 {view==="questionnaire"&&<div className="form"><div className="toolbar"><h1>{t.profile}</h1><button className="btn light" onClick={()=>setView("home")}>{t.back}</button></div><div className="card"><div className="grid">{fields.map(f=><div className={"field "+(f.type==="textarea"?"full":"")} key={f.key}><label>{f.label}</label>{f.type==="select"?<select value={q[f.key]??""} onChange={e=>setQ({...q,[f.key]:e.target.value})}><option value="">Select…</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:f.type==="textarea"?<textarea value={q[f.key]??""} onChange={e=>setQ({...q,[f.key]:e.target.value})}/>:<input type={f.type==="number"?"number":"text"} value={q[f.key]??""} onChange={e=>setQ({...q,[f.key]:f.type==="number"?Number(e.target.value):e.target.value})}/>}</div>)}</div><div className="actions"><button className="btn primary" onClick={save} disabled={loading}>{loading?t.loading:t.save}</button></div></div></div>}
 {view==="candidates"&&<><div className="toolbar"><div><h1>{t.candidates}</h1><p className="muted">Profiles are filtered and then negotiated by two AI clones.</p></div><button className="btn light" onClick={()=>setView("questionnaire")}>{t.profile}</button></div>{candidates.length?<div className="candidate-grid">{candidates.map(c=><div className="card" key={c.id}><div className="person"><div className="avatar">{c.name[0]}</div><div><h3>{c.name}</h3><p className="muted">{c.questionnaire.city} · {c.questionnaire.occupation}</p></div></div><div className="tags"><span className="tag">{c.questionnaire.budget_min}–{c.questionnaire.budget_max} TND</span><span className="tag">{c.questionnaire.sleep}</span><span className="tag">{c.questionnaire.cleanliness}</span></div><button className="btn primary" onClick={()=>run(c)} disabled={loading}>{loading?t.loading:t.match}</button></div>)}</div>:<div className="card"><p>{t.no}</p></div>}</>}
 {view==="result"&&selected&&<><div className="toolbar"><h1>{t.why} {selected.other?.name||log?.participants?.find((n:string)=>n!==user.name)}</h1><button className="btn light" onClick={()=>setView("matches")}>{t.back}</button></div><div className="card"><div className="statusrow"><span className={"status "+selected.status}>{statusLabel(selected.status,lang)}</span><span className="score">{selected.score}/100</span></div><p>{selected.summary}</p><div className="scoregrid">{Object.entries(selected.scores||{}).filter(([k])=>k!=="overall").map(([k,v])=><div className="scorebox" key={k}><b>{String(v)}</b><div className="muted">{k}</div></div>)}</div>{selected.positives?.length>0&&<div className="section"><h3>✓ Shared ground</h3>{selected.positives.map((x:string)=><p key={x}>{x}</p>)}</div>}{selected.frictions?.length>0&&<div className="section"><h3>⚠ Friction</h3>{selected.frictions.map((x:string)=><p key={x}>{x}</p>)}</div>}{selected.compromise&&<div className="section"><h3>🤝 Compromise</h3><p>{selected.compromise}</p></div>}<div className="section"><h3>{t.negotiation}</h3><div className="conversation">{log?.conversation?.map((x:any)=><div className="turn" key={x.turn}><b>{x.speaker||x.role}</b><span className="muted"> · {x.phase||""}</span><div>{x.message||x.content}</div></div>)}</div></div></div></>}
 {view==="matches"&&<><div className="toolbar"><h1>{t.matches}</h1><button className="btn primary" onClick={loadCandidates}>{t.candidates}</button></div>{matches.length?<div className="candidate-grid">{matches.map(m=><div className="card" key={m.id}><div className="person"><div className="avatar">{m.other.name[0]}</div><div><h3>{m.other.name}</h3><span className={"status "+m.status}>{statusLabel(m.status,lang)}</span></div></div><div className="score">{m.score}/100</div><p className="muted">{m.summary}</p><button className="btn light" onClick={()=>openLog(m)}>{t.why}</button></div>)}</div>:<div className="card"><p>{t.no}</p></div>}</>}
 {view==="clone"&&<div className="chat"><div className="toolbar"><div><h1>{t.clone}</h1><p className="muted">Your clone uses only your saved questionnaire.</p></div><button className="btn light" onClick={()=>setView("home")}>{t.back}</button></div><div className="card"><div className="messages">{messages.map((m,i)=><div key={i} className={"bubble "+(m.role==="user"?"user":"bot")}>{m.content}</div>)}{loading&&<div className="bubble bot">{t.loading}</div>}</div><div className="chatbar"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder={t.placeholder}/><button className="btn primary" onClick={send}>{t.send}</button></div></div></div>}
 </main></div>
}